config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"	
  resources :comments do
  	collection do
  		get 'get_last_comment_id_plus'
  	end
  end
  post 'comment_by_task' => 'comments#comment_by_task'
  post 'save_comment' => 'comments#save_comment'
  # get 'get_last_comment_id' => 'comments#get_last_comment_id'
  devise_for :users
  resources :tasks do
  	collection do
  		delete :multiple_delete
  	end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user 
	belongs_to :task
	validates_presence_of :content
end

app/models/task.rb
class Task < ApplicationRecord
	attr_accessor :comments_attributes	
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates_presence_of :description, :deadline
	accepts_nested_attributes_for :comments
	# attr_access

	def is_late?
		if Time.now > self.deadline
			return "late-task"
		end
	end

	def self.search(term)
		if term 
			where("description LIKE ?","%#{term}%")
		else
			all
		end
	end

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :comments_attributes	
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_comment, only: [:show,:edit,:update,:destroy]
before_action :set_comments_by_task, only: [:create,:comment_by_task]
respond_to :html, :json ,:js

	def new
		@comment = Comment.new()
	end

	def create
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id #method provided by devise 

		if @comment.save
			# redirect_to tasks_path , notice: 'Your post was create succesfully'
				render :file => "comments/comments_refresher.js.erb" 	
				# redirect_to tasks_path		
			else
				# render :file => "comments/comments_refresher.js.erb" 
				render :new		
		end	
	end

	def edit
	end

	def index
		@comments = Comment.all
	end

	def comment_by_task
		@comment = Comment.new(:task_id => @task_id)
	end

	def update
		if @comment.update(comment_params)
			redirect_to comments_path, notice: "Successfully updated task"
		else
			render :edit
		end		
	end

	def destroy
		@task_id = @comment.task_id # destroy method cannot use set_comment_by_tasks because we use defulat RestRouting
		@comments = Comment.where(:task_id => @task_id)
		@comment.destroy
		render :file => "comments/comments_refresher.js.erb" , notice: 'Your comment was deleted succesfully'
	end

	def save_comment
		@task_id = params[:task_id]
		# @new_comment_id = (Comment.last.id)+1
		render 'save_comment'
	end

	def get_last_comment_id_plus
		@new_comment_ids = Comment.last.id+1
		respond_to do |format|
			format.json {render json: @new_comment_ids}
		end
	end


	private

	def comment_params
		params.require(:comment).permit(:content,:task_id)
	end	

	def set_comments_by_task
		@task_id = comment_params[:task_id]
		@comments = @comments = Comment.where(:task_id => @task_id)
	end

	def  set_comment
		@comment = Comment.find(params[:id])
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:show,:edit,:update,:destroy]
respond_to :html, :json

	def index
		@tasks = Task.search(params[:search]).order('priority asc')
		@new_description = params[:search]
		if @tasks.count == 0
			puts "in loop"
			@add_button = "Add"
		else
			@add_button = "Search"
		end
	end

	def edit
	end

	def update
		if @task.update(task_params)
			redirect_to tasks_path
		else
			render :edit
		end
	end

	def destroy
		@task.destroy
		redirect_to tasks_path, notice: 'Your task was deleted succesfully'	
	end

	def new
		@task = Task.new(:priority => 10)
	end

	def create
		@task = Task.new(task_params)
		@task.user_id = current_user.id #method provided by devise 
		@tasks = Task.all.order('priority asc')

		respond_to do |format|
			if @task.save
				format.html { redirect_to tasks_path, notice: 'Your task was create succesfully' }
				format.js {render :create, notice: 'Your task was create succesfully' }
			else
				format.html { render  :new }
				format.js { render :create , notice: 'There is some error cannot create new task'}
			end
		end
	end

	def multiple_delete
		@tasks_id = params[:task_ids]
		Task.where(:id => @tasks_id ).destroy_all

		redirect_to tasks_path
	end

	private

	def task_params
		params.require(:task).permit(:deadline, :description,:priority)
	end	

	def  set_task
		@task = Task.find(params[:id])		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def is_on_page?(paths)
		on_page = true

		paths.each do |path|
			on_page = false if current_page?(path)
		end

		return on_page

	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_comment_form.html.erb
<%= form_for @comment,class: "form-horizontal" do |f| %>

	<div class="form-group">
		<%= f.label "Add comment",class: "control-label" %>
		<%= f.text_area :content,class: "form-control" %>
		<%= f.submit 'Save', class: 'btn btn-primary' %>
	</div>		


	<div class="form-group", style= "display:none">
		<%= f.label :task_id,class: "col-sm-2 control-label" %>
		<%= f.text_field :task_id,class: "form-control" %>
	</div>		

<% end %>

app/views/comments/_comment_list_by_task.html.erb
<td class="col-md-3", id= "add-on-text-<%= @task_id %>" >
	<div id= "comments_list_section_<%= @task_id %>">
	<hr>
	<% if @comments.count > 0 %>
		<% @comments.each do |comment| %>
			<%= best_in_place comment, :content, as: :textarea %>
			<%= link_to '', comment_path(comment), remote: true,method: :delete, id: "delete_comment_#{comment.id}_from_index", data: { confirm:"Are you sure ?" } , class: "glyphicon glyphicon-trash" %>
			<div class="col-md-offset-10">
				<span> <%=link_to comment.user.email,"#" %></span>
			</div>
		<hr>
		<% end %>
	<% end %>	
	</div>
	<%# render 'comments/comment_form' %>
	<%= render 'comments/new_comment_form' %>
</td>

app/views/comments/_new_comment_form.html.erb
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

<%= text_area_tag 'comment_content',nil,size: "75X5",class: "new_comment_text_area",id: "comment_area_#{@task_id}" %>

<div>
<%= link_to "Test save", save_comment_path(:task_id => @task_id) , :remote => true, :method => "post" %>
</div>

app/views/comments/comment_by_task.js.erb
if($("#add-on-text-<%= @task_id %>").length > 0) {
	$("#task_row_<%= @task_id %>").children("td").remove();
}
else
{
	$("#task_row_<%= @task_id %>").append("<%= j (render 'comments/comment_list_by_task') %>");
}

app/views/comments/comments_refresher.js.erb
$("#task_row_<%= @task_id %>").children("td").remove();
$("#task_row_<%= @task_id %>").append("<%= j (render 'comments/comment_list_by_task') %>");

app/views/comments/edit.html.erb
<%= render 'comment_form' %>

app/views/comments/index.html.erb
<%= @comments.inspect %>

app/views/comments/new.html.erb
<%= render 'comment_form' %>

app/views/comments/save_comment.js.erb
task_id = <%= @task_id %>

comment_content = $("#comment_area_"+task_id).val()
console.log(comment_content)


$.ajax({
	type: 'GET',
	url: '/comments/get_last_comment_id_plus',
	dataType:"json",
	success:function(result){
		new_comment_id = result
		console.log(new_comment_id)

		html_string_1 ='<span data-bip-type="textarea" data-bip-attribute="content" data-bip-object="comment" data-bip-original-content='+comment_content+' data-bip-skip-blur="false" data-bip-url="/comments/'+ new_comment_id +'" data-bip-value='+comment_content+' class="best_in_place" id="best_in_place_comment_'+ new_comment_id +'_content">'+comment_content+'</span>' ; 
		html_string_2 = '<a id="delete_comment_<%= @task_id %>_from_index" data-confirm="Are you sure ?" class="glyphicon glyphicon-trash" data-remote="true" rel="nofollow" data-method="delete" href="/comments/'+ new_comment_id +'"></a>'     
		html_string_3 = '<div class="col-md-offset-10"><span> <a href="#">test@test.com</a></span></div><hr>'  
		html_string = html_string_1+html_string_2+html_string_3
		console.log(html_string)

		$.ajax({
			type: 'POST',
			url: '/comments',
			dataType: 'JSON',
			data: {
				comment: {
					content: comment_content,
					task_id: task_id
				},

    		success: function(){
        		alert('success')
				// $("#task_row_<%= @task_id %>").children("td").remove();
				$("#comments_list_section_<%= @task_id %>").append(html_string)
      		}		
			}
		});


  }
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShipnityTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class = "container col-xs-8 col-xs-offset-2"> 

	<div class = "row">
		<div class="col-md-12" >
			<%= render 'shared/nav' %>
			<%= yield %>

		<%= js add_gritter(flash[:notice], title: "Task Manager Notification", sticky: false,time: 2000) %>			
		</div>
	</div>
	
</body>
</html>

app/views/shared/_nav.html.erb
<% navbar_readonly =  is_on_page?([tasks_path,root_path]) %>

<div class = 'logo'>
  <h1>Task Manager</h1>
</div>

<div class="nav navbar-default">
     <%= form_tag tasks_path , :method => 'get',id: "tasks_search", class: "navbar-form" do %>
        <div class="form-group" style="display:inline;">
          <div class="input-group" style="display:table;">
            <span class="input-group-addon" style="width:1%;">
                <%= link_to "", new_task_path, class: "glyphicon glyphicon-plus" %>
            </span>
            <%= text_field_tag :search,nil,class: "form-control",:readonly => navbar_readonly, placeholder: "Search or Add new task",autocomplete: :off  %>
            <span class="input-group-btn" style="width:1%;", id = "button_span">
              <%= render 'tasks/search_button' %>
            </span>
          </div>
        </div>
       <% end %> 
</div>

app/views/tasks/_form.html.erb
<hr>
<%= form_for @task, class: "form-horizontal" do |f| %>

	<div class="form-group">
		<%= f.label :description,class: "col-sm-2 control-label" %>
		<%= f.text_area :description,class: "form-control" %>
	</div>	

	<div class="form-group">
		<%= f.label :deadline,class: "col-sm-2 control-label" %>
		<%= f.date_field :deadline,class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :priority,class: "col-sm-2 control-label" %>
		<%= f.text_field :priority,class: "form-control" %>
	</div>		
	
	<%= f.submit 'Save', class: 'btn btn-primary btn-block' %>

<% end %>

app/views/tasks/_nav_create_new_button.html.erb
<% navbar_readonly =  is_on_page?([tasks_path,root_path]) %>

<%= link_to 'Add Task',
        '/tasks?' + {task: {deadline: 5.days.from_now, description: @new_description.to_s,priority:"10"}}.to_param, 
        method: :post, 
        class: 'btn btn-primary btn-block',id: "add_new_button",
        remote: true,
        :readonly => navbar_readonly %>

app/views/tasks/_search_button.html.erb
<% navbar_readonly =  is_on_page?([tasks_path,root_path]) %>

<%= submit_tag 'Search', class: 'btn btn-primary btn-block', id:"search_button" ,:readonly => navbar_readonly %>

app/views/tasks/_search_form.html.erb
		<%= form_tag "", class: "form-horizontal" do %>
				<%= text_field_tag :search %>
		<% end %>

app/views/tasks/_task.html.erb
<tr class= "<%= task.is_late? %>">
	<td class="text-center", id="checkbox-td-<%= task.id %>">
		<span class= "glyphicon glyphicon-th-list check_box_before", data-id= <%= task.id %> ></span>
	</td>

	<td class="col-md-8", id= "task_row_<%= task.id.to_s %>">
		<%= best_in_place task, :description, as: :textarea %>
	</td>
	<td class="text-center">
		<%= link_to '',comment_by_task_path(:comment => { :task_id => task.id} ), class: "glyphicon glyphicon-comment" ,:remote => true, :method=> "post"%>
	</td>
	<td class="text-center">
		<%= link_to '', edit_task_path(task), class: "glyphicon glyphicon-pencil" %>
	</td>
	<td class="text-center">
		<%= link_to '', task_path(task),method: :delete, id: "delete_task_#{task.id}_from_index", data: { confirm:"Are you sure ?" } , class: "glyphicon glyphicon-trash" %>
	</td>					
</tr>

app/views/tasks/_tasks_table.html.erb
<%= render @tasks %>


<tr class="delete_tasks_row">
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td class= "text-center delete_tasks_col">
	<a class= "glyphicon glyphicon-trash" id="delete-tasks-button" href="tasks/delete_all?" method="post"></a>
	</td>
</tr>

app/views/tasks/create.js.erb
$("#search").val("")

$("#tasks").html("<%= j (render @tasks) %>");

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
 <%=form_tag multiple_delete_tasks_path, method: :delete do%>
<table class="table table-hover table-bordered" class="main_table">
	<thead>
	</thead>
	<tbody id= "tasks">		
		<%= render @tasks %> <%# this will make rails render partial wiht _post.html.erb name and rails will auromatic do the |post| %>
</tr>
	</tbody>
</table>

<a class= "col-md-offset-10 col-md-3" id="delete-tasks-button" style="display:none"><%= button_tag  "Delete selected" %></a>
</div>
<% end %>

app/views/tasks/index.js.erb
$("#tasks").html("<%= j (render @tasks) %>");

if ( "<%=@add_button%>" == "Add") {
	if($("input#search_button").length > 0 ) { 
		$("#button_span").children("input#search_button").remove();
		$("#button_span").append("<%= j (render 'tasks/nav_create_new_button') %>") ; 
	} else {
		$("a#add_new_button").remove()
		$("#button_span").append("<%= j (render 'tasks/nav_create_new_button') %>")  
		// we have to render the button because we need to update @new_description value that pass to element
		// if we not rerender the value will stuck at the first value that trigger this function
	}

} else if ( ( "<%=@add_button%>" == "Search") ){

	if($("a#add_new_button").length > 0 ) { 
		$("#button_span").children("a#add_new_button").remove();
		$("#button_span").append("<%= j (render 'tasks/search_button') %>") ; 
	} else
	{
		$("input#search_button").remove()
		$("#button_span").append("<%= j (render 'tasks/search_button') %>")  		
	}

}

app/views/tasks/new.html.erb
<%= render 'form' %>